### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

### ISSUE THREAD

**Issue by SkeletonOne** [conansherry/detectron2#11]
I am using VS2019. When running python setup.py build develop, it shows

Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

I have already installed 14.0 with 'Microsoft Visual C++ Build Tools', and I can find 'Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.24210' in my system. Can anybody help me? Thanks!

**Comment by deeptigoyal** [comment]
Am facing the similar issues.  @SkeletonOne  have you been able to resolve it. Kindly help

**Comment by SkeletonOne** [comment]
@deeptigoyal Well actually no, I was force to move to Ubuntu.
