### ISSUE TITLE
Windows 10 detectron2 + pytorch 1.4 DLL Load Failed

### ISSUE THREAD

**Issue by apiszcz** [conansherry/detectron2#6]
Updated to pytorch 1.4.
When I try to build detectron2 (which works with pythorch 1.3)

    from detectron2 import _C
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by sean-wade** [comment]
Hi! How did you solve this problem? Thanks!

**Comment by apiszcz** [comment]
in my case
(base) C:\g2\vr>pip install "git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI"


recompile detectron2

**Comment by sean-wade** [comment]
> in my case
> (base) C:\g2\vr>pip install "git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI"
> 
> recompile detectron2

OK, thanks! I'll try it...

**Comment by hejinsome** [comment]
@apiszcz @a954217436 Hi! did you solve this problem?  I meet the same preblem.

**Comment by solarflarefx** [comment]
@apiszcz When you say "recompile detectron2" do you mean you ran:

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
cd detectron2
python setup.py build develop
